name: scan-images

on:
  schedule:
    - cron: "0 12 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    strategy:
      matrix:
        branch: [ main, release-1.3, release-1.2 ]
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag=v3.5.0
      with:
        ref: ${{ matrix.branch }}
    - name: Setup go
      uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # tag=v3.4.0
      with:
        go-version: 1.19
    - name: Run verify container script
      run: make verify-container-images